GET http://localhost:3000/api/notes
# GET https://notes-api-clean-architecture.alexgalhardo.com/api/notes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NWM4Mjc3OGMxYjFhZTIxMDUyNmNmNCIsImlhdCI6MTcxNzMzODc0NSwiZXhwIjoxNzE5OTMwNzQ1fQ.e2Y-wwx6B38BblaCL7RnrbCFEqc9GAv8BZjbz2LGGOs
User-Agent: 665c82778c1b1ae210526cf4
