POST http://localhost:3000/api/signin
# POST https://notes-api-clean-architecture.alexgalhardo.com/api/signin
Content-Type: application/json

{
	"email": "test@gmail.com",
	"password": "mypasswordtest123"
}
